In [ ]:
import json
import pandas as pd
import numpy as np
from pandas import json_normalize
from sklearn import linear_model
from sklearn.metrics import r2_score, mean_squared_error, f1_score
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import plotly.express as px
import matplotlib.pyplot as plt

In [ ]:
with open('/content/drive/MyDrive/allHouses2.json','r', encoding='utf-8') as json_file:
    data = json.load(json_file)
totalData = data.get('data')
df = json_normalize(totalData)
df.columns

Index(['identifier', 'title', 'totalPrice', 'unitPrice', 'images', 'age',
       'floorArea', 'floorAreaUnit', 'numOfBeds', 'numberOfParking',
       'description', 'seoDescription', 'bread_crumbs',
       'location.locationName', 'location.longitude', 'location.latitude',
       'location.targetGlobalLocation.id',
       'location.targetGlobalLocation.type', 'type.landuseType',
       'type.propertyType', 'features.parking', 'features.lobby',
       'features.warehouse', 'features.sports_hall', 'features.guard',
       'features.elevator', 'features.balcony', 'features.swimming_pool',
       'features.sauna', 'features.air_conditioning',
       'features.conference_hall', 'features.roof_garden',
       'features.remote_door', 'features.jacuzzi', 'features.central_antenna',
       'contact.type', 'contact.fullName', 'contact.callNumber',
       'contact.departmentName', 'contact.departmentLogoUrl',
       'contact.departmentId', 'contact.whatsappAvailibility', 'graph.content',
       '

In [ ]:
df.drop('features.null', axis=1, inplace=True)

In [ ]:
recordFeatures = {
    'پارکینگ': 'parking',
    'لابی': 'lobby',
    'انباری': 'warehouse',
    'سالن ورزش': 'sports_hall',
    'نگهبان': 'guard',
    'آسانسور': 'elevator',
    'بالکن': 'balcony',
    'استخر': 'swimming_pool',
    'سونا': 'sauna',
    'تهویه مطبوع': 'air_conditioning',
    'سالن اجتماعات': 'conference_hall',
    'روف گاردن': 'roof_garden',
    'درب ریموت': 'remote_door',
    'جکوزی': 'jacuzzi',
    'آنتن مرکزی': 'central_antenna',
}
features = ['totalPrice', 'floorArea', 'numOfBeds']
recordFeaturesColumns=[]
for item in recordFeatures.items():
  recordFeaturesColumns.append('features.' + item[1])
regions=[]
for item in df['bread_crumbs']:
  regions.append(item[3].split(' ')[1])
df['region']=regions
features.append('region')
features.extend(recordFeaturesColumns.copy())
df = df[features]
df

totalPrice  floorArea  numOfBeds region  features.parking  \
0     3.100000e+09       47.0        1.0      3             False   
1     1.449500e+10      223.0        4.0      3             False   
2     1.540000e+10      134.0        2.0      3             False   
3     6.950000e+09      109.0        2.0      4             False   
4     5.600000e+09       94.0        2.0      4             False   
...            ...        ...        ...    ...               ...   
3537  1.585000e+10      145.0        3.0      2             False   
3538  8.500000e+09      113.0        2.0      2             False   
3539  3.380000e+10      260.0        3.0      1             False   
3540  7.020000e+10      390.0        4.0      1             False   
3541  1.608000e+11      670.0        4.0      1             False   

      features.lobby  features.warehouse  features.sports_hall  \
0              False                True                 False   
1              False                True                 False   
2               True                True                 False   
3              False                True                 False   
4              False                True                 False   
...              ...                 ...                   ...   
3537            True                True                 False   
3538           False                True                 False   
3539            True                True                  True   
3540            True                True                  True   
3541            True                True                  True   

      features.guard  features.elevator  features.balcony  \
0              False               True             False   
1              False               True              True   
2               True               True             False   
3              False               True              True   
4              False               True              True   
...              ...                ...               ...   
3537            True               True              True   
3538            True               True              True   
3539            True               True              True   
3540            True               True              True   
3541            True               True              True   

      features.swimming_pool  features.sauna  features.air_conditioning  \
0                      False           False                       True   
1                      False           False                       True   
2                      False           False                       True   
3                      False           False                      False   
4                      False           False                      False   
...                      ...             ...                        ...   
3537                   False           False                      False   
3538                   False           False                      False   
3539                    True            True                       True   
3540                    True            True                       True   
3541                    True            True                       True   

      features.conference_hall  features.roof_garden  features.remote_door  \
0                        False                 False                  True   
1                        False                 False                  True   
2                        False                 False                  True   
3                        False                 False                  True   
4                        False                 False                  True   
...                        ...                   ...                   ...   
3537                     False                 False                  True   
3538                     False                 False                  True   
3539                      True                  Tr

In [ ]:
df.dropna(inplace=True)
df

totalPrice  floorArea  numOfBeds region  features.parking  \
0     3.100000e+09       47.0        1.0      3             False   
1     1.449500e+10      223.0        4.0      3             False   
2     1.540000e+10      134.0        2.0      3             False   
3     6.950000e+09      109.0        2.0      4             False   
4     5.600000e+09       94.0        2.0      4             False   
...            ...        ...        ...    ...               ...   
3537  1.585000e+10      145.0        3.0      2             False   
3538  8.500000e+09      113.0        2.0      2             False   
3539  3.380000e+10      260.0        3.0      1             False   
3540  7.020000e+10      390.0        4.0      1             False   
3541  1.608000e+11      670.0        4.0      1             False   

      features.lobby  features.warehouse  features.sports_hall  \
0              False                True                 False   
1              False                True                 False   
2               True                True                 False   
3              False                True                 False   
4              False                True                 False   
...              ...                 ...                   ...   
3537            True                True                 False   
3538           False                True                 False   
3539            True                True                  True   
3540            True                True                  True   
3541            True                True                  True   

      features.guard  features.elevator  features.balcony  \
0              False               True             False   
1              False               True              True   
2               True               True             False   
3              False               True              True   
4              False               True              True   
...              ...                ...               ...   
3537            True               True              True   
3538            True               True              True   
3539            True               True              True   
3540            True               True              True   
3541            True               True              True   

      features.swimming_pool  features.sauna  features.air_conditioning  \
0                      False           False                       True   
1                      False           False                       True   
2                      False           False                       True   
3                      False           False                      False   
4                      False           False                      False   
...                      ...             ...                        ...   
3537                   False           False                      False   
3538                   False           False                      False   
3539                    True            True                       True   
3540                    True            True                       True   
3541                    True            True                       True   

      features.conference_hall  features.roof_garden  features.remote_door  \
0                        False                 False                  True   
1                        False                 False                  True   
2                        False                 False                  True   
3                        False                 False                  True   
4                        False                 False                  True   
...                        ...                   ...                   ...   
3537                     False                 False                  True   
3538                     False                 False                  True   
3539                      True                  Tr

In [ ]:
for item in recordFeaturesColumns:
  df[item]=df[item].astype('category').cat.codes
df

totalPrice  floorArea  numOfBeds region  features.parking  \
0     3.100000e+09       47.0        1.0      3                 0   
1     1.449500e+10      223.0        4.0      3                 0   
2     1.540000e+10      134.0        2.0      3                 0   
3     6.950000e+09      109.0        2.0      4                 0   
4     5.600000e+09       94.0        2.0      4                 0   
...            ...        ...        ...    ...               ...   
3537  1.585000e+10      145.0        3.0      2                 0   
3538  8.500000e+09      113.0        2.0      2                 0   
3539  3.380000e+10      260.0        3.0      1                 0   
3540  7.020000e+10      390.0        4.0      1                 0   
3541  1.608000e+11      670.0        4.0      1                 0   

      features.lobby  features.warehouse  features.sports_hall  \
0                  0                   1                     0   
1                  0                   1                     0   
2                  1                   1                     0   
3                  0                   1                     0   
4                  0                   1                     0   
...              ...                 ...                   ...   
3537               1                   1                     0   
3538               0                   1                     0   
3539               1                   1                     1   
3540               1                   1                     1   
3541               1                   1                     1   

      features.guard  features.elevator  features.balcony  \
0                  0                  1                 0   
1                  0                  1                 1   
2                  1                  1                 0   
3                  0                  1                 1   
4                  0                  1                 1   
...              ...                ...               ...   
3537               1                  1                 1   
3538               1                  1                 1   
3539               1                  1                 1   
3540               1                  1                 1   
3541               1                  1                 1   

      features.swimming_pool  features.sauna  features.air_conditioning  \
0                          0               0                          1   
1                          0               0                          1   
2                          0               0                          1   
3                          0               0                          0   
4                          0               0                          0   
...                      ...             ...                        ...   
3537                       0               0                          0   
3538                       0               0                          0   
3539                       1               1                          1   
3540                       1               1                          1   
3541                       1               1                          1   

      features.conference_hall  features.roof_garden  features.remote_door  \
0                            0                     0                     1   
1                            0                     0                     1   
2                            0                     0                     1   
3                            0                     0                     1   
4                            0                     0                     1   
...                        ...                   ...                   ...   
3537                         0                     0                     1   
3538                         0                     0                     1   
3539                         1                    

In [ ]:
df['region']=df['region'].astype('int')
df.dtypes

totalPrice                   float64
floorArea                    float64
numOfBeds                    float64
region                         int64
features.parking                int8
features.lobby                  int8
features.warehouse              int8
features.sports_hall            int8
features.guard                  int8
features.elevator               int8
features.balcony                int8
features.swimming_pool          int8
features.sauna                  int8
features.air_conditioning       int8
features.conference_hall        int8
features.roof_garden            int8
features.remote_door            int8
features.jacuzzi                int8
features.central_antenna        int8
dtype: object

In [ ]:
x = np.asanyarray(df[df.columns.difference(['totalPrice'])])
y = np.asanyarray(df['totalPrice'])
print(x)
print(y)

[[  1.   0.   0. ...  47.   1.   3.]
 [  1.   1.   0. ... 223.   4.   3.]
 [  1.   0.   0. ... 134.   2.   3.]
 ...
 [  1.   1.   1. ... 260.   3.   1.]
 [  1.   1.   1. ... 390.   4.   1.]
 [  1.   1.   1. ... 670.   4.   1.]]
[3.1000e+09 1.4495e+10 1.5400e+10 ... 3.3800e+10 7.0200e+10 1.6080e+11]


In [ ]:
import torch
import torch.nn as nn

In [ ]:
numeric_x_columns = list(df.columns)
numeric_x_columns.remove('totalPrice')
numeric_y_columns = ['totalPrice']
numeric_x_columns

['floorArea',
 'numOfBeds',
 'region',
 'features.parking',
 'features.lobby',
 'features.warehouse',
 'features.sports_hall',
 'features.guard',
 'features.elevator',
 'features.balcony',
 'features.swimming_pool',
 'features.sauna',
 'features.air_conditioning',
 'features.conference_hall',
 'features.roof_garden',
 'features.remote_door',
 'features.jacuzzi',
 'features.central_antenna']

In [ ]:
numeric_x_df = pd.DataFrame(df, columns=numeric_x_columns)
numeric_y_df = pd.DataFrame(df, columns=numeric_y_columns)
numeric_y_df.head(2)

totalPrice
0  3.100000e+09
1  1.449500e+10

In [ ]:
numeric_x = torch.tensor(numeric_x_df.values, dtype=torch.float)
numeric_y = torch.tensor(numeric_y_df.values, dtype=torch.float)

In [ ]:
print(numeric_x.shape)
print(numeric_y.shape)

torch.Size([3095, 18])
torch.Size([3095, 1])


In [ ]:
class Net(nn.Module):
    def __init__(self, D_in, H1, H2, H3, D_out):
        super(Net, self).__init__()
        
        self.linear1 = nn.Linear(D_in, H1)
        self.linear2 = nn.Linear(H1, H2)
        self.linear3 = nn.Linear(H2, H3)
        self.linear4 = nn.Linear(H3, D_out)
        
    def forward(self, x):
        y_pred = self.linear1(x).clamp(min=0)
        y_pred = self.linear2(y_pred).clamp(min=0)
        y_pred = self.linear3(y_pred).clamp(min=0)
        y_pred = self.linear4(y_pred)
        return y_pred

In [ ]:
H1, H2, H3 = 500, 1000, 200
D_in, D_out = numeric_x.shape[1], numeric_y.shape[1]

In [ ]:
model1 = Net(D_in, H1, H2, H3, D_out)
criterion = nn.MSELoss(reduction='sum')
criterion2= nn.modules.loss.CrossEntropyLoss()
optimizer = torch.optim.SGD(model1.parameters(), lr=0.01)

In [ ]:
means, maxs, mins = dict(), dict(), dict()
for col in df:
    means[col] = df[col].mean()
    maxs[col] = df[col].max()
    mins[col] = df[col].min()
print(means)

{'totalPrice': 20284969577.396446, 'floorArea': 124.53747980613893, 'numOfBeds': 2.27108239095315, 'region': 4.916639741518578, 'features.parking': 0.0, 'features.lobby': 0.3977382875605816, 'features.warehouse': 0.92859450726979, 'features.sports_hall': 0.20161550888529886, 'features.guard': 0.3421647819063005, 'features.elevator': 0.794184168012924, 'features.balcony': 0.6591276252019386, 'features.swimming_pool': 0.16478190630048464, 'features.sauna': 0.17705977382875607, 'features.air_conditioning': 0.3760904684975767, 'features.conference_hall': 0.24491114701130856, 'features.roof_garden': 0.1987075928917609, 'features.remote_door': 0.4852988691437803, 'features.jacuzzi': 0.18804523424878836, 'features.central_antenna': 0.4051696284329564}


In [ ]:
numeric_data = (df - df.mean()) / (df.max() - df.min())

In [ ]:
numeric_x_df = pd.DataFrame(numeric_data, columns=numeric_x_columns)
numeric_y_df = pd.DataFrame(numeric_data, columns=numeric_y_columns)

In [ ]:
numeric_x = torch.tensor(numeric_x_df.values, dtype=torch.float)
numeric_y = torch.tensor(numeric_y_df.values, dtype=torch.float)

In [ ]:
class Net2(nn.Module):
    def __init__(self,D_in, H1, H2, H3, D_out):
        super(Net2, self).__init__()
        # linear layer (784 -> 1 hidden node)
        self.fc1 = nn.Linear(D_in, H1)
        self.fc2 = nn.Linear(H1, H2)
        self.fc3 = nn.Linear(H2, H3)
        self.fc3 = nn.Linear(H3, D_out)
        self.dropout = nn.Dropout(0.2)

    def forward(self, x):
        # flatten image input
        # x = x.view(-1, 28 * 28)
        # add hidden layer, with relu activation function
        x = nn.ReLU(self.fc1(x))
        x = self.dropout(x)
        x = nn.ReLU(self.fc2(x))
        x = self.dropout(x)
        x = nn.ReLU(self.fc3(x))
        return x

In [ ]:
model3 = Net2(D_in, H1, H2, H3, D_out)
criterion = nn.MSELoss(reduction='sum')
optimizer = torch.optim.Adam(model3.parameters(), lr=1e-4 * 2)

In [ ]:
losses2 = []
print(numeric_x.shape)
print(numeric_y.shape)
print(numeric_x)
for t in range(500):
    y_pred = model3(numeric_x)
    print(y_pred.shape)
    loss = criterion(y_pred, numeric_y)
    print(t, loss.item())
    losses2.append(loss.item())
    
    # if torch.isnan(loss):
    #     break
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

torch.Size([3095, 18])
torch.Size([3095, 1])
tensor([[-0.0625, -0.0847, -0.0913,  ...,  0.5147, -0.1880, -0.4052],
        [ 0.0793,  0.1153, -0.0913,  ...,  0.5147, -0.1880, -0.4052],
        [ 0.0076, -0.0181, -0.0913,  ...,  0.5147, -0.1880, -0.4052],
        ...,
        [ 0.1092,  0.0486, -0.1865,  ...,  0.5147,  0.8120,  0.5948],
        [ 0.2139,  0.1153, -0.1865,  ...,  0.5147,  0.8120,  0.5948],
        [ 0.4395,  0.1153, -0.1865,  ...,  0.5147,  0.8120,  0.5948]])


TypeError: ignored